In [15]:
!pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5567 sha256=483759812223cbf4ff1a1ed8eeb4f156167648164291dc54a5fbcd9bc5d87a49
  Stored in directory: c:\users\kruth\appdata\local\pip\cache\wheels\21\1d\b2\768b65901d249c6eb2a8d9c30392506555a4e94055ba4e0aa0
Successfully built word2number


In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from word2number import w2n

In [3]:
df=pd.read_excel('Book1.xlsx')
df

Area  Bedrooms  Age  Price
0  2600         3   20  55000
1  3000         4   15  56500
2  3200         4   18  61000
3  3600         3   30  59500
4  4000         5    8  76000

In [5]:
reg=linear_model.LinearRegression()
reg.fit(df[['Area','Bedrooms','Age']],df.Price)

LinearRegression()

In [6]:
reg.coef_

array([   16.54764549, -7249.111506  , -1072.52332297])

In [7]:
reg.intercept_

54390.27099067073

In [9]:
reg.predict([[3000,3,15]])

C:\Users\kruth\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([66198.02310084])

## Excersice Question

In [11]:
d=pd.read_csv('hiring.csv')
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [12]:
d.experience=d.experience.fillna("zero")
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
d.experience=d.experience.apply(w2n.word_to_num)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [18]:
import math
median_test_score=math.floor(d['test_score(out of 10)'].mean())
median_test_score

7

In [19]:
d['test_score(out of 10)']=d['test_score(out of 10)'].fillna(median_test_score)
d

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [21]:
reg2=linear_model.LinearRegression()
reg2.fit(d[['experience','test_score(out of 10)','interview_score(out of 10)']],d['salary($)'])


LinearRegression()

In [24]:
reg2.predict([[12,10,10]])

C:\Users\kruth\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])